window_title: "中国象棋 - 北京科技大学"
think_time: 30
pgn_game: "Chinese Chess"
pgn_event: "null"
pgn_site: "null"
pgn_round: "0"
pgn_red_name: "参赛队 A"
pgn_black_name: "参赛队 B"
pgn_red_elo: ""
pgn_black_elo: ""
pgn_ecco: "0"
pgn_opening: ""
pgn_variation: ""
pgn_fen: "rnbakabnr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RNBAKABNR r"
